version: '2.1'

orbs:
  terraform: circleci/terraform@3.1

jobs:
  terraform_init:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./Terraform

  terraform_plan:
    executor: terraform/default
    steps:
      - checkout
      - terraform/plan:
          path: ./Terraform

  terraform_apply:
    executor: terraform/default
    steps:
      - checkout
      - terraform/apply:
          path: ./Terraform

workflows:
  main:
    jobs:
      - terraform_init
      - terraform_plan:
          requires:
            - terraform_init
      - terraform_apply:
          requires:
            - terraform_plan

