version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: 
          command: echo "deploy"

  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - run: 
          command: echo "deploy"

workflows:
  version: 2

  stage_workflow:
    jobs:
      - build
      - deploy
